'''
Created on Nov 15, 2016

@author: achaluv
'''
from scipy.cluster.hierarchy import dendrogram, linkage
import numpy as np

import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d.axes3d as p3
from sklearn.cluster import AgglomerativeClustering

data=[]
with open('achaluv_clustering_data.txt','r') as f:
    num = 0
    for line in f:
        nums = line.split(',')
        data.append([float(nums[0]),float(nums[1]),float(nums[2])])
    data = np.array(data)
Z = linkage(data)

plt.figure(figsize=(25, 10))
plt.title('Hierarchical Clustering Dendrogram')
plt.xlabel('sample index')
plt.ylabel('distance')
dendrogram(
    Z,
    leaf_rotation=90.,  # rotates the x axis labels
    leaf_font_size=8.,  # font size for the x axis labels
)

plt.show()

ward = AgglomerativeClustering(n_clusters=2, linkage='ward').fit(data)
label = ward.labels_

fig = plt.figure()
ax = p3.Axes3D(fig)
#ax.view_init(7, -80)
for l in np.unique(label):
    ax.plot3D(data[label == l, 0], data[label == l, 1], data[label == l, 2],
              'o', color=plt.cm.jet(np.float(l) / np.max(label + 1)))
plt.title('Clusters generated by hierarchical clustering')   
plt.show() 


plt.title('Hierarchical Clustering Dendrogram - Last 10 clusters')
plt.xlabel('sample index or (cluster size)')
plt.ylabel('distance')
dendrogram(
    Z,
    truncate_mode='lastp',  # show only the last p merged clusters
    p=10,  # show only the last p merged clusters
    leaf_rotation=90.,
    leaf_font_size=12.,
    show_contracted=True,  # to get a distribution impression in truncated branches
)
plt.show()
